CREATE ROLE aadmin WITH 
  LOGIN 
  PASSWORD 'contrasenasegura123!';


GRANT CONNECT ON DATABASE nba_stats TO aadmin;


GRANT USAGE ON SCHEMA public TO aadmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO aadmin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO aadmin;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aadmin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE ON SEQUENCES TO aadmin;